CREATE TABLE PATIENT
(
    ID					INT PRIMARY KEY AUTO_INCREMENT,
    FIRSTNAME			VARCHAR(30),
    LASTNAME			VARCHAR(30),
    EMERGENCY_CONTACT   VARCHAR(15),
    FORBIDDEN_AREA		VARCHAR(256),
    CREATED				TIMESTAMP DEFAULT NOW()
);