CREATE TABLE PATIENT
(
    ID					INT PRIMARY KEY AUTO_INCREMENT,
    FIRSTNAME			VARCHAR(30),
    LASTNAME			VARCHAR(30),
    EMERGENCY_CONTACT   VARCHAR(15),
    FORBIDDEN_AREA		VARCHAR(256),
    CREATED				TIMESTAMP DEFAULT NOW(),
    TAGID				VARCHAR(45) NOT NULL
);

CREATE TABLE CAREGIVER
(
	ID					INT PRIMARY KEY AUTO_INCREMENT,
	FIRSTNAME			VARCHAR(30),
	LASTNAME			VARCHAR(30),
	USERNAME			VARCHAR(50) NOT NULL,
	CG_PWD				VARCHAR(50) NOT NULL
);

CREATE TABLE EMERTASK
(
    ID					INT PRIMARY KEY AUTO_INCREMENT,
    LOCATION			VARCHAR(30),
    PATIENT_ID			INT(10),
    TASK_STATUS   		VARCHAR(15),
	RELATED_CG_ID		INT(10),
    START_TIME			TIMESTAMP DEFAULT NOW(),
    END_TIME			TIMESTAMP,
	FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(ID),
	FOREIGN KEY (RELATED_CG_ID) REFERENCES CAREGIVER(ID)
);